//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Language_3ISP97_TuzhilovDvoryaninov.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_ClientDetails
    {
        public string NameClient { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public Nullable<decimal> Age { get; set; }
        public Nullable<int> TagCount { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> LastVisit { get; set; }
    }
}
